apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nomad
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nomad
    app.kubernetes.io/part-of: nomad
  name: nomad
spec:
  ports:
  - port: 1
    targetPort: 1
  selector:
    app.kubernetes.io/instance: nomad
status:
  loadBalancer: {}
